import { useRef, useEffect, forwardRef, useImperativeHandle } from 'react';

interface TableRow {
  qNo: string;
  a: string;
  b: string;
  c: string;
  total: string;
}

interface ResultCanvasProps {
  headerInfo: Record<string, string>;
  tableData: TableRow[];
  totalMarks: {
    calculated: number;
    written: number;
    bubbleDigits: number;
  };
  isValid: boolean;
}

export interface ResultCanvasRef {
  downloadImage: () => void;
}

export const ResultCanvas = forwardRef<ResultCanvasRef, ResultCanvasProps>(
  ({ headerInfo, tableData, totalMarks, isValid }, ref) => {
    const canvasRef = useRef<HTMLCanvasElement>(null);

    useImperativeHandle(ref, () => ({
      downloadImage: () => {
        const canvas = canvasRef.current;
        if (!canvas) return;
        
        const link = document.createElement('a');
        link.download = 'ocr-result.png';
        link.href = canvas.toDataURL('image/png');
        link.click();
      }
    }));

    useEffect(() => {
      const canvas = canvasRef.current;
      if (!canvas) return;

      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      const width = 800;
      const height = 700;
      canvas.width = width;
      canvas.height = height;

      // Background
      ctx.fillStyle = '#0f1419';
      ctx.fillRect(0, 0, width, height);

      // Header gradient
      const headerGrad = ctx.createLinearGradient(0, 0, width, 80);
      headerGrad.addColorStop(0, '#14b8a6');
      headerGrad.addColorStop(1, '#0891b2');
      ctx.fillStyle = headerGrad;
      ctx.fillRect(0, 0, width, 80);

      // Title
      ctx.fillStyle = '#0f1419';
      ctx.font = 'bold 28px Inter, sans-serif';
      ctx.fillText('OCR Extraction Result', 30, 50);

      // Document Info Section
      ctx.fillStyle = '#22d3ee';
      ctx.font = 'bold 14px Inter, sans-serif';
      ctx.fillText('DOCUMENT INFORMATION', 30, 120);

      ctx.fillStyle = '#94a3b8';
      ctx.font = '12px Inter, sans-serif';
      let y = 145;
      Object.entries(headerInfo).forEach(([key, value], idx) => {
        const col = idx % 2 === 0 ? 30 : 400;
        if (idx % 2 === 0 && idx > 0) y += 25;
        ctx.fillStyle = '#64748b';
        ctx.fillText(key.toUpperCase() + ':', col, y);
        ctx.fillStyle = '#e2e8f0';
        ctx.fillText(value || '-', col + 100, y);
      });

      // Table Section
      y += 50;
      ctx.fillStyle = '#22d3ee';
      ctx.font = 'bold 14px Inter, sans-serif';
      ctx.fillText('MARKS TABLE', 30, y);

      // Table header
      y += 30;
      ctx.fillStyle = '#1e293b';
      ctx.fillRect(30, y - 18, 740, 30);
      
      ctx.fillStyle = '#94a3b8';
      ctx.font = 'bold 12px Inter, sans-serif';
      const cols = [50, 200, 320, 440, 600];
      const headers = ['Q.NO', 'A', 'B', 'C', 'TOTAL'];
      headers.forEach((h, i) => ctx.fillText(h, cols[i], y));

      // Table rows
      ctx.font = '14px JetBrains Mono, monospace';
      tableData.forEach((row, idx) => {
        y += 28;
        if (idx % 2 === 0) {
          ctx.fillStyle = '#1e293b50';
          ctx.fillRect(30, y - 18, 740, 28);
        }
        ctx.fillStyle = '#e2e8f0';
        ctx.fillText(row.qNo, cols[0], y);
        ctx.fillText(row.a || '-', cols[1], y);
        ctx.fillText(row.b || '-', cols[2], y);
        ctx.fillText(row.c || '-', cols[3], y);
        ctx.fillStyle = '#22d3ee';
        ctx.fillText(row.total || '-', cols[4], y);
      });

      // Validation Section
      y += 60;
      const validColor = isValid ? '#22c55e' : '#ef4444';
      ctx.strokeStyle = validColor;
      ctx.lineWidth = 2;
      ctx.strokeRect(30, y - 10, 740, 100);
      
      ctx.fillStyle = validColor + '20';
      ctx.fillRect(30, y - 10, 740, 100);

      ctx.fillStyle = validColor;
      ctx.font = 'bold 18px Inter, sans-serif';
      ctx.fillText(isValid ? '✓ VALIDATION PASSED' : '✗ VALIDATION FAILED', 50, y + 25);

      ctx.font = '14px Inter, sans-serif';
      ctx.fillStyle = '#94a3b8';
      ctx.fillText('Calculated Sum:', 50, y + 55);
      ctx.fillText('Written Total:', 250, y + 55);
      ctx.fillText('Bubble Digits:', 450, y + 55);

      ctx.fillStyle = '#e2e8f0';
      ctx.font = 'bold 20px JetBrains Mono, monospace';
      ctx.fillText(totalMarks.calculated.toString(), 170, y + 55);
      ctx.fillText(totalMarks.written.toString(), 365, y + 55);
      ctx.fillText(totalMarks.bubbleDigits.toString(), 565, y + 55);

      // Footer
      ctx.fillStyle = '#475569';
      ctx.font = '11px Inter, sans-serif';
      ctx.fillText('Generated by OCR Document Extractor', 30, height - 20);
      ctx.fillText(new Date().toLocaleString(), width - 180, height - 20);

    }, [headerInfo, tableData, totalMarks, isValid]);

    return (
      <canvas 
        ref={canvasRef} 
        className="w-full h-auto rounded-xl border border-border shadow-lg"
      />
    );
  }
);

ResultCanvas.displayName = 'ResultCanvas';
